version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: gui_agent_loop_core-backend
    ports:
      - "9000:9000"
    volumes:
      - ./work:/app/work
    environment:
      - BACKEND_DIR=/app/work
    networks:
      - app-network
    hostname: backend
    # entrypoint: ["python", "-m", "app.main"]

networks:
  app-network:
    driver: bridge
