version: '3.8'

services:
  backend:
    build:
      context: ./llm_code_navigator/backend
      dockerfile: Dockerfile
    image: llm_code_navigator-backend_test
    ports:
      - "9000:9000"
    volumes:
      - ./work:/app/work
    environment:
      - BACKEND_DIR=/app/work
    networks:
      - app-network
    hostname: backend
    entrypoint: ["python", "-m", "app.main"]

  frontend:
    build:
      context: ./llm_code_navigator/frontend
      dockerfile: Dockerfile
    image: llm_code_navigator-frontend_test
    ports:
      - "3001:3001"
    networks:
      - app-network
    hostname: frontend

networks:
  app-network:
    driver: bridge